@host = localhost:8080
// Register User
POST http://{{host}}/api/user/register HTTP/1.1
content-type: application/json

{
    "name": "Mike",
    "username": "swozey",
    "email": "mike@@mikej.dev",
    "password": "123465789"
}
###

